### ISSUE TITLE
pretty_columns doesn't match column_names

### ISSUE THREAD

**Issue by mastef** [jsoma/tabletop#100]
If there's e.g. merged cells, or empty column cells then pretty_columns and column_names don't match up anymore. Disabling prettyColumnNames fixes this behaviour, but how do I get the pretty names afterwards? :-(

**Comment by mastef** [comment]
I managed it temporarily by replacing the loadPrettyColumns function, with the following. It does a check if the column_name starts with a '_', which indicates an empty cell. ( Is this reliable? In the test data empty cells started mostly with '_c' ). In that case it skips the pretty Columns assigning.

It also does the same gsx test as in the column_names function

```js
              Tabletop.Model.prototype.loadPrettyColumns = function(data) {
                var pretty_columns = {};
                var column_names = this.column_names;

                var i = -1;
                var j = -1;

                for(var key in this.raw.feed.entry[0]){
                  if(/^gsx/.test(key)){
                    j++;
                    if(column_names[j].indexOf('_') !== 0){
                      i++;
                      if (typeof data.feed.entry[i].content.$t !== 'undefined') {
                        pretty_columns[column_names[j]] = data.feed.entry[i].content.$t;
                      } else {
                        pretty_columns[column_names[i]] = column_names[i];
                      }
                    }
                  }
                }

                this.pretty_columns = pretty_columns;

                this.prettifyElements();
                this.ready();
              }
```

**Comment by carlosmiguelsns** [comment]
Thanks for the tip...
I just made a change to get empty columns value
```javascript
if (typeof data.feed.entry[i].content.$t !== 'undefined') {
       ... ... ...
} else {
       pretty_columns[column_names[j]] = "";
}
```

**Comment by jsoma** [comment]
It's four hundred years later, but I can't seem to reproduce this one.
