### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by AGresvig** [jsoma/tabletop#104]
GDrive had a service interruption today, which resulted in Tabletop not being able to fetch data (obviously). The code threw an unexpected error:

```
for(i = 0, ilen = data.feed.entry.length; i < ilen ; i++) {
                                 ^
TypeError: Cannot read property 'entry' of undefined
```

[Here](https://github.com/jsoma/tabletop/blob/master/src/tabletop.js#L309).

Can this be wrapped in a try/catch so it won't crash the app running it?

Thanks!

**Comment by frankrowe** [comment]
Yeah, we need some sort of error handling.

I added a test for `data.feed` before the loop. If it doesn't exist, I pass an error as the third argument to the main callback.

`Tabletop.init({callback: function(data, tabletop, err) {}})`

https://github.com/frankrowe/tabletop/blob/error-handling/src/tabletop.js#L308

**Comment by enjalot** [comment]
+1 i'm using tabletop in an app where users can paste in their url. I'd love to be able to handle incorrect pastes or invalid sheets with grace by catching the error.

**Comment by AGresvig** [comment]
FWIW, we solved this using NodeJS `domains` (ES6 example):

````javascript
    import domain from 'domain';
    
    await new Promise((resolve) => {
      const googleSheetDomain = domain.create();
      googleSheetDomain.on('error', (e) => {
        console.error('Problem while data fetching from Google Sheets');
        console.log(e);
        resolve();
      });
      googleSheetDomain.run(() => this.fetchDataFromGoogleSheets(site, pages).then(resolve));
    });
````

Not optimal but better than silent crash

**Comment by enjalot** [comment]
@AGresvig yes i'm getting around it with a global error handler in the browser, but I feel it would be much better to design for the failure case in the library.

**Comment by tarundhillon** [comment]
@AGresvig are you able to catch the XMLHttpRequest Network Error using your global error handler, I am assuming you are using window.onerror () ?

**Comment by jsoma** [comment]
Fixed!
