### ISSUE TITLE
Getting error: "Uncaught ReferenceError: process is not defined"

### ISSUE THREAD

**Issue by ezmiller** [jsoma/tabletop#107]
This error occurs when I load tabletop at the end of the body element like so:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.3.min.js"><\/script>')</script>
<script src="js/vendor/tabletop.js"></script>
<script src="js/main.js"></script>
```

When I commented out [Lines#5-8](https://github.com/jsoma/tabletop/blob/master/src/tabletop.js#L5-L8), the error disappeared and the script seemed to function as expected.

**Comment by jsoma** [comment]
That's my punishment for not testing code before I merge in PR's! Thanks for the heads up, fixed - had to throw quotes around the `undefined` on line 5.
