### ISSUE TITLE
Would like the ability to grab a sheet in a single request

### ISSUE THREAD

**Issue by samscode** [jsoma/tabletop#108]
I have a document with several sheets. I just want to pull back 1 sheet, but it seems to do two requests. Is there any way to avoid the 1st request and just perform the second? This is what I have at the moment...

Tabletop.init( { key: sheet_key,
			callback: showData,
			wanted: ["Sheet2"],
			prettyColumnNames: false,
			simpleSheet: true } );

**Comment by jsoma** [comment]
Unfortunately Tabletop always has to run at least two requests - the first gets the URLs of all of the specific sheets, and the second one gets the actual content of those sheets. Even though you're only pulling one sheet, it still needs to get the table of contents to know where to find it.
