### ISSUE TITLE
Initial GET request returns 400 status code if data is moved to multiple sheets

### ISSUE THREAD

**Issue by cdvillard** [jsoma/tabletop#117]
I'm working with v1.3.4 right now. My initially published data was in a single worksheet and worked perfectly . . .

![Screenshot showing a Google Spreadsheet with a single worksheet working well with tabletop.js](https://i.imgur.com/cUv4VJf.jpg)

but after moving the data to multiple sheets, it breaks the initial GET request.

![Screenshot showing a Google Spreadsheet with multiple worksheets not working well with tabletop.js](https://i.imgur.com/Pgo5qlm.jpg)

You can see my code doesn't include the `simpleSheet` property, and I can't find any indication of something missing to work with multiple worksheets. I'd hate for this to be an "Is it everyone or just me?" moment, but is it?

**Comment by cdvillard** [comment]
I will note that upgrading to the latest version fixes this, but I'll leave this open in case @jsoma cares to address it.

**Comment by jsoma** [comment]
Cleaning up issues! Thanks for letting me know about this, glad to see we didn't have anyone else stumble in here with the sample trouble in the past few years :)
