### ISSUE TITLE
Is this suitable for use in a banner campaign?

### ISSUE THREAD

**Issue by tommypreger** [jsoma/tabletop#119]
I need a very simple database for a banner campaign to store latitude/longitude for a bunch of addresses. The client wants to be able to easily add more addresses during the campaign.
Tabletop.js + google drive works perfectly for this, but I'm worried we might have trouble with the amount of requests we're likely to generate. Has anyone done this before and can comment?
Or, if you can point me in the direction of a better (but equally simple) solution that would be very welcome!
Thanks!

**Comment by bastole** [comment]
Don't use it for production. Especially banners - way too much exposure.

https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwiPorm-rL3QAhXEmpQKHbrBBe0QFgggMAE&url=https%3A%2F%2Fgist.github.com%2Fjsvine%2F3295633&usg=AFQjCNGl8YAQOWmqwB5FwI-azfBXTSP_aA&sig2=7Y6C3B-0GGMre_pH2JMAXQ&bvm=bv.139250283,d.dGc&cad=rja

Also note that recently Google has blocked the use of public asset from google drive for banner campaign(DoubleClick) and is forcing devs to use Asset Library instead.

**Comment by jsoma** [comment]
Thanks, @bastole, you've def hit the nail on the head.
