### ISSUE TITLE
How many people can be reading from the table top ?

### ISSUE THREAD

**Issue by fabzl** [jsoma/tabletop#121]
HI guys, 
This tool is great and I use it for several websites. But Im wondering if there is a limit of users that can open the google doc at the same time. for editing is 50 but it really doesn't say for table top . 
Many thanks

**Comment by jsoma** [comment]
It would be a limit from Google - it should be much higher than the editing one, but I don't think anyone has found an actual number. If you plan on a lot of traffic you might want to look at the [caching options](https://github.com/jsoma/tabletop#cachingproxying-google-spreadsheets).
