### ISSUE TITLE
Google Spreadsheet from JSON?

### ISSUE THREAD

**Issue by ChristosChristofidis** [jsoma/tabletop#122]
Is it possible to create a new google sheet with information contained in JSON ?

**Comment by mroswell** [comment]
This is a helpful tool. You could create a CSV from the JSON file, and import it into the Google Sheet. https://konklone.io/json/

**Comment by ChristosChristofidis** [comment]
I mean, I am trying to avoid the manual import .

**Comment by mroswell** [comment]
I just found this: https://gist.github.com/chrislkeller/5719258

**Comment by jsoma** [comment]
Cleaning up issues, thanks for the tip @mroswell!
