### ISSUE TITLE
New public URL from google spreadsheet

### ISSUE THREAD

**Issue by laurenbenichou** [jsoma/tabletop#128]
Hey folks!

So I am getting this new public url `https://docs.google.com/spreadsheets/d/e/2PACX-1vS_-xyhRcOQxfG1FRlztvU03-kRrBJhzNTTFvpE7w57YT2d7H6a1UheojbAETAiAIhZXvnEnz4tIRNK/pubhtml.`

I tried it with the latest release of tabletop.js, and even tried it with the code on master, to no avail. I get a 400 error. 

Only solution was to actually use the spreadsheet id with the old url, like this `https://docs.google.com/spreadsheets/d/SPREADSHEET_ID/pubhtml.` Hopefully, you have a PR on the way. 

Just wanted to flag it.

**Comment by charith93** [comment]
changing the new public url to old url, worked for me. Thank you @laurenbenichou . I hope this gets fixed asap.

**Comment by heenaI** [comment]
@charith93  how did you change the url to the old one?

**Comment by laurenbenichou** [comment]
@heenaI when you're on the spreadsheet page, check out the url.
![screen shot 2016-11-29 at 10 39 33 am](https://cloud.githubusercontent.com/assets/5431395/20723639/2db29f4e-b620-11e6-9127-1d6a369b0495.png)
 The spreadsheet id is there. Copy it and replace it in this url: `https://docs.google.com/spreadsheets/d/SPREADSHEET_ID_HERE/pubhtml.`

**Comment by laurenbenichou** [comment]
Don't forget to still publish your spreadsheet.

**Comment by thaddeusm** [comment]
Using the share link instead of the link provided when 'publishing to the web' seems to solve the problem.

**Comment by jsoma** [comment]
Is everyone getting these `/d/e` links when they're publishing to the web? I can't seem to create one for the life of me, every Publish link seems to work.

**Comment by laurenbenichou** [comment]
@jsoma Yes. If you still want to use Tabletop.js, use the solution above with the id in the spreadsheet URL and the old URL - `https://docs.google.com/spreadsheets/d/SPREADSHEET_ID_HERE/pubhtml`
