### ISSUE TITLE
"Invalid query parameter value for sq" When Specifying Query Value

### ISSUE THREAD

**Issue by Mac-lp3** [jsoma/tabletop#129]
Hi,

I am having trouble with the query interface and am not sure if I have found a bug, or if it is just an error on my part.

Essentially, I am able to get all of my spreadsheet data when I do not provide a query. When I do provide one, I get ``Invalid query parameter value for sq``. 

My plain text query string is: ``Select * where B = 3 and H = "Democrat"``.
And Tabletop encodes it as: ``Select%20*%20where%20B%20=%20%2202%22%20and%20H%20=%20%22Democrat%22`` 

Looking at the source, if the ``query`` parameter is specified Tabletop will append ``&sq=ENCODED_QUERY`` to the url.

However, according to [these docs](https://developers.google.com/chart/interactive/docs/querylanguage#setting-the-query-in-the-data-source-url), the query parameter is actually ``/gviz/tq?tq=ENCODED_STRING``. The encoded string above works when I use it with the API described in these docs.

I also noticed that the URL described in those docs is a bit different from the one Tabletop uses, but I believe this was mentioned in another issue.

Does anyone have any suggestions on how to get the query working?

Thanks

**Comment by jsoma** [comment]
Queries wound up being a lot of trouble! If anyone wants to fix them up I'm happy to entertain a PR.
