### ISSUE TITLE
Request to spredsheet.google.com returns "Unknown visibility value.". Causing failed JSON parsing.

### ISSUE THREAD

**Issue by henggana** [jsoma/tabletop#130]
When I use tabletop with published sheet url, JSON parse error raised. Before that, request to spreadsheet.google.com is returned "Unknown visibility value." (400).

It was working fine last week.

**Comment by henggana** [comment]
Example published url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRCibY5CxWTwkIcX7QtXRn-ddTT-7h4TmT5LaB9qIo76BcCzRkueHc2Mgzs22MNM2c-SnUiEkZRxD4H/pubhtml

The error on chrome developer console:
https://cldup.com/Y4--x54SN9.png

**Comment by john-guerra** [comment]
+1

**Comment by teknologika** [comment]
+2

**Comment by henggana** [comment]
It works if use the sheet url. Still need to publish it first.

**Comment by henggana** [comment]
Duplicate with #128, same solution too! Closing.
