### ISSUE TITLE
README bad link

### ISSUE THREAD

**Issue by rocketpan** [jsoma/tabletop#133]
There's a link to a built by balance domain that's now being parked at godaddy.  Intentional?

**Comment by jsoma** [comment]
You deserve a very tall trophy that says "convinced a really lazy guy to start cleaning up his very old and unattractive documentation"

**Comment by rocketpan** [comment]
If it makes you feel better, this is the first and possibly only contribution I will make to open source software.  So maybe you deserve a very tall trophy for convincing an open source lurker to contribute!

Also: worth revisiting https://github.com/jsoma/tabletop/issues/132
