### ISSUE TITLE
Can you please update the examples

### ISSUE THREAD

**Issue by d3netxer** [jsoma/tabletop#136]
two links seem to be broken, and I am having a hard time of finding examples

**Comment by jsoma** [comment]
What links are broken? All of the examples seem to work for me. You'll want to download the repository as a zip file, extract it, and then look at the files inside of `examples/`

![image](https://cloud.githubusercontent.com/assets/95126/21610006/90e0b04a-d193-11e6-8bdb-bba61809aace.png)
