### ISSUE TITLE
share working example at codepen.io please

### ISSUE THREAD

**Issue by pleabargain** [jsoma/tabletop#137]
I've tried your samples found here and pasted them at codepen. 
e.g. step two paste in the code of the README.md
but no joy | No data | console is empty

Here's the codepen showing same:
http://codepen.io/pleabargain/pen/bgGwme

thank you

**Comment by jsoma** [comment]
You just needed to include the Tabletop library, then call `init()` - http://codepen.io/anon/pen/WRNpRQ
