### ISSUE TITLE
404 prevents access to json

### ISSUE THREAD

**Issue by mroswell** [jsoma/tabletop#147]
Every year I deliver a tabletop-based map to an advocacy organization. This year I can't seem to get access to the underlying sheet's JSON. 

This is related to this issue:
https://stackoverflow.com/questions/40740118/has-the-google-sheets-published-url-suddenly-changed-to-a-different-format

My ID after sharing starts with 2PACX, which doesn't match the original spreadsheet ID. It's also a much longer ID

I replace the public_spreadsheet_url variable with the new URL:

`var public_spreadsheet_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vScwAw01j5Ua7M4J7Ui1Va9iOwvKChSJJKJBmREVK1D38Hpr20QY33EPRvcIGZk7u_svdeMGRQPSwx9/pubhtml';`

and I get a 404 error, when tabletop tries to access the ../basic?alt=json url:
`spreadsheets.google.com/feeds/worksheets/e/2PACX-1vScwAw01j5Ua7M4J7Ui1Va9iOwvKChSJJKJBmREVK1D38Hpr20QY33EPRvcIGZk7u_svdeMGRQPSwx9/public/basic?alt=json Failed to load resource: the server responded with a status of 404 ()`

In that stackoverflow issue above, the URL suddenly changed back again, and all was well in the world. But even when I create a brand new sheet, I get those long 2PACX IDs that don't work

For now I'm going to try using the old sheet, and just adding new worksheets to it. But I'm hoping there is a better solution, moving forward.

I'm guessing that #136 is also an (unspecified) example of the same issue.

Perhaps this will come in handy.
https://developers.google.com/sheets/api/guides/migration

**Comment by mroswell** [comment]
I found a URL that gives me JSON access to my data: https://spreadsheets.google.com/feeds/list/1fv6M6R9Ogo2TGAlxOKKgOouVBW7NilkCwppc4tpEFm8/1/public/values?alt=json-in-script&callback=jsonp_1504027469196_63202

note that this doesn't use the same ID that is delivered from the File > Publish to the Web link. When I use that, I get: 
`JSONP request to https://spreadsheets.google.com/feeds/list/2PACX-1vScwAw01j5Ua7M4J7Ui1Va9iOwvKChSJJKJBmREVK1D38Hpr20QY33EPRvcIGZk7u_svdeMGRQPSwx9//1/public/values?alt=json-in-script failed`

I don't really know what to do with this information in terms of tabletop, but I thought I'd share it. The source was:
https://medium.freecodecamp.org/get-sheet-done-using-google-spreadsheets-as-your-data-backend-650ba23dc6d9

I found the link in devtools, after running this:
https://giladaya.github.io/get-sheet-done/

with this ID:
1fv6M6R9Ogo2TGAlxOKKgOouVBW7NilkCwppc4tpEFm8

**Comment by mroswell** [comment]
A few notes:
1. I had success if I use the original ID on the spreadsheet, and not the separate and unrelated `File > Publish to the web` link or ID.
2. So, this line of the README will need to be amended, changing: `You pass in either key as the actual spreadsheet key, or just the full published-spreadsheet URL.`
to
`Pass in the spreadsheet key found in the URL in the address bar (not the key that you get from the "Publish to the web" link`
(or something like that.)

2. There might have been some other voodoo, too. 
 - Check `Automatically republish when changes are made` in the `File > Publish to the web` dialog box.

**Comment by jsoma** [comment]
Thanks for spending so much time on this! We encountered a similar issue a while back, you might be interested in [this section of the README](https://github.com/jsoma/tabletop#if-your-publish-to-web-url-doesnt-work). Sometimes the publish key doesn't work and you need to use the Share one. It's a mystery as to what's going on, though.

**Comment by seiyria** [comment]
I can't seem to get this to work with any spreadsheet url, has this been broken further? I also can't seem to get a url without /d/e for whatever that's worth.

**Comment by jsoma** [comment]
Hm, Not that I can tell. I just worked on a brand new spreadsheet this morning using the technique above (Share > copy the URL), although it only had `/d/` and not `/d/e`. Sorry it's causing trouble!

**Comment by mroswell** [comment]
Did you see my detail comment above: https://github.com/jsoma/tabletop/issues/147#issuecomment-326151962
If I remember correctly, I didn't include the whole URL, just the ID portion 

And recently the File > Publish to the Web ID didn't work for me. I just copied the ID from the URL in the browser. Particularly if you have a URL that looks like this:
https://docs.google.com/spreadsheets/d/SOMESTRING/edit#gid=SOMENUMBER

you want the SOMESTRING, not the SOMENUMBER.

I'll be interested to know if this detail helps.

**Comment by seiyria** [comment]
hi @mroswell,

When you say I want SOMESTRING, does that mean that I initialize tabletop.js with just the id? I've been using the entire link.
