### ISSUE TITLE
Issue with postProcess

### ISSUE THREAD

**Issue by Spectre5** [jsoma/tabletop#148]
postProcess occurs before fetchPrettyColumns.  First off, that means that means you need to use the google short names (no space, all lowercase, etc), which is fine enough but should be mentioned in the guide.  More concerning is that if you add a column in postProcess, then prettyColumnNames must be set to false, otherwise when fetchPrettyColumns is executed, the added column is lost.  At the least this should be stated in the guide, but fixing it in the code may not be too difficult either.

**Comment by jsoma** [comment]
Thanks for this!
