### ISSUE TITLE
Most straightforward way to disaggregate tabletop once the spreadsheet is final?

### ISSUE THREAD

**Issue by mroswell** [jsoma/tabletop#149]
Now that the spreadsheet is final, I'm guessing I'll get faster load time if I just start with a JSON file. Can anyone provide simple guidelines for doing that?

**Comment by jsoma** [comment]
Use [Mr. Data Converter](https://shancarter.github.io/mr-data-converter/) to convert your CSV into JSON. Should work well! Then include it as `var data = .....` if you'd like to skip out on the headache of reading a separate file.

**Comment by mroswell** [comment]
Mr. Data Converter offers 4 different JSON formats: 
Properties, Column Arrays, Row Arrays, Dictionary.
Do you know which one is advised?

**Comment by jsoma** [comment]
You'll want `JSON-Properties` 👍
