### ISSUE TITLE
Provide way to get sheet gid

### ISSUE THREAD

**Issue by candrews** [jsoma/tabletop#153]
I'd like to be able to create links that will take the user to a specific sheet in a document. Links to specific sheets take the form:
`https://docs.google.com/spreadsheets/d/<DOCID>/edit#gid=<GID>`

I haven't been able to find any way for tabletop to give me the GID of a sheet - can you please provide that ability?

**Comment by jsoma** [comment]
Happy to entertain a PR if someone comes up with one!
