### ISSUE TITLE
How to use wait without Backbone?

### ISSUE THREAD

**Issue by ddazal** [jsoma/tabletop#155]
That's it, if I use the `wait` option, how do I initialize the data request? I'm assuming this is done with `fetch` but is not working. 

I want to do the following: I'm building the request as a module
```javascript
import tabletop from 'tabletop'

function requestSheet (key, cb) {
    return Tabletop.init({
        key: key,
        callback: cb,
        wait: true
    })
}

module.exports = { requestSheet }
```
When I import that module into another file I just want to get the data
```javascript
import { requestSheet } from 'path/to/module'

const key = 'some url'
const cb = (data, tabletop) => {
    // do stuff but this really doesn't work
}

requestSheet(key, cb) // what else? requestSheer(key, cb).fetch() does not work
```
Deep down all I want to do is that `requestSheet` function return the value of `data` or `tabletop` so I can just `const data = requestSheet(key, cb, sheetName /* maybe */)`

Can anybody help me? Thanks

**Comment by jsoma** [comment]
Just went ahead and popped in an example, give it a look and you should be good to go. And yup, `.fetch` is going to be your buddy here.
