### ISSUE TITLE
README confusion... also, "/d/e"?

### ISSUE THREAD

**Issue by kylebakerio** [jsoma/tabletop#157]
README glosses over an important option. When publishing, you are given the ability to publish as webpage, csv, tsv, etc. Which should we select?

Based on seeing "/pubhtml" on the end of the example URL, I assumed webpage was the only option as one point and this lib is based on that, so went with that. Should it be updated to handle a newer format, though? Or am I missing something entirely?

Next: I'm only getting a link with "/d/e" in it. Refreshing isn't solving that. It feels pretty crazy to see a comment in the instructions just say "that's bad--just try refreshing", with no explanation of what's going on, or no knowledge that refreshing will help eventually, or ever, or what in the world is going on.

It seems like there are other ways besides that URL that would be less ambiguous, like using an ID copied from the URL itself. I haven't gotten that far yet, but... maybe that'd be a better strategy for the readme demo, to avoid this /d/e weirdness?

I guess my point is, this readme intro isn't given me a strong lead as a new user here.

Thanks for the library, though, I'm glad it exists. Seems like lots of great work.

Cheers.

**Comment by finetype** [comment]
had looked [here](https://github.com/jsoma/tabletop/issues/128), but looking a second time it looks like there are some solutions--using the share (instead of publish) url, and grabbing the id from the viewing url and copying onto a url of a specific format.

I've used the second option--seems to work when putting it into the address bar, so that's promising.

That gets me a successful ping to google, and I see in the network that it's finding the right spreadsheet because the response has the correct author field (the person who shared the document with me), but it's empty--the callback just logs an empty array, unfortunately. :/

will post when I resolve.

**Comment by finetype** [comment]
next problem was due to inconsistent internet--I had read the bit that you cannot have blank rows. the spreadsheet I had had blank rows beneath the first row. I had tried fixing that by adding 'ignore' to the blank rows in one column, but that save hadn't propogagted to google sheets because of a glitch on the page it seems.

What is interesting is that even that first row didn't show up in that case. Weird.

**Comment by erikawashere** [comment]
I'm having the same problem.  I used the sharing link and its just not working.  Anyone else figure this out?

**Comment by kylebakerio** [comment]
yeah, I did figure it out. Do you still need help?

I ended up using this method:
```javascript
loadGSheet = () => {
	Tabletop.init({
		key: '1dsdqf0vmAv_389X9anXP7_XN78Xv9EbN3p9yNxU-1kw',
		simpleSheet: true,
		callback: (data, tabletop) => m.redraw(), // console.log("finished loadGSheet", data) 
		postProcess: row => rowHandlers[row.type](row),
	});
}
```

Notice the 'key'? that's just an id taken out of the url. That's all you have to pass in. iirc, I guess the documentation is a little fallen behind.

**Comment by erikawashere** [comment]
Thanks for your help, but this didn't work either for some reason.

I'm sorry to be a bother, but is something out of order or do I need to
remove something? Is that why its not running?

<script src='
https://cdnjs.cloudflare.com/ajax/libs/tabletop.js/1.5.1/tabletop.min.js
'></script>
<script type='text/javascript'>

var publicSpreadsheetUrl =
'*https://docs.google.com/spreadsheets/d/1Oe_C2GkBJKnD5lm0TwOtP3oXasjtEnMiqxt2ScH13pc/edit?usp=sharing
<https://docs.google.com/spreadsheets/d/1Oe_C2GkBJKnD5lm0TwOtP3oXasjtEnMiqxt2ScH13pc/edit?usp=sharing>*
';

function init() {
  Tabletop.init( { key: publicSpreadsheetUrl,
                   callback: showInfo,
                   simpleSheet: true } )
}

function showInfo(data, tabletop) {
  alert('Successfully processed!')
  console.log(data);
}

window.addEventListener('DOMContentLoaded', init)

</script>


// pull data from google spreadsheet
$(document).ready(function() {
    var spreadsheet_url = "
https://docs.google.com/spreadsheets/d/1Oe_C2GkBJKnD5lm0TwOtP3oXasjtEnMiqxt2ScH13pc/edit?usp=sharing
"
    Tabletop.init({
        key: spreadsheet_url,
        callback: writeTableWith,
        simpleSheet: true,
        debug: true
    });
})

function writeTableWith (data) {
    console.log("Read in", data)

loadGSheet = () => {
Tabletop.init({
key: '1Oe_C2GkBJKnD5lm0TwOtP3oXasjtEnMiqxt2ScH13pc',
simpleSheet: true,
callback: (data, tabletop) => m.redraw(), // console.log("finished
loadGSheet", data)
postProcess: row => rowHandlers[row.type](row),
});
}

function writeTableWith (data) {
    console.log("Read in", data)
}

// create table headers
function createTableColumns(){

    /* swap out the properties of mDataProp & sTitle to reflect
    the names of columns or keys you want to display.
    Remember, tabletop.js strips out spaces from column titles, which
    is what happens with the More Info column header */

    var tableColumns =   [
{"mDataProp": "citation", "sTitle": "Citation", "sClass": "center"},
{"mDataProp": "generaldescription", "sTitle": "General Description",
"sClass": "center"},
{"mDataProp": "applicability", "sTitle": "Applicability", "sClass":
"center"}
];
    return tableColumns;
}

// create the table container and object
function writeTableWith(dataSource){

    jqueryNoConflict("#demo").html("<table cellpadding='0' cellspacing='0'
border='0' class='display table table-bordered table-striped'
id='data-table-container'></table>");

    var oTable = jqueryNoConflict("#data-table-container").dataTable({
        "sPaginationType": "bootstrap",
        "iDisplayLength": 25,
        "aaData": dataSource,
        "aoColumns": createTableColumns(),
        "fnRowCallback": function(nRow, aData, iDisplayIndex) {
            console.log(aData);
            $("td:eq(2)", nRow).html("<a href='http://" + aData.website +
"'>Website</a>");
            return nRow;
        },
        "oLanguage": {
            "sLengthMenu": "_MENU_ records per page"
        }
    });

};

//define two custom functions (asc and desc) for string sorting
jQuery.fn.dataTableExt.oSort["string-case-asc"]  = function(x,y) {
return ((x < y) ? -1 : ((x > y) ?  0 : 0));
};

jQuery.fn.dataTableExt.oSort["string-case-desc"] = function(x,y) {
return ((x < y) ?  1 : ((x > y) ? -1 : 0));
};

**Comment by kylebakerio** [comment]
your 'publicSpreadsheetUrl' looks completely wrong... Not only does it ignore what I said in my last post, it just looks like a broken link altogether.

I think that's because you didn't post it as code, but as text, so github tried to turn it into a link. Please use markdown to indicate it is text.

Did you just paste an old version, or what? Because in my example, I showed how to not use the URL at all and just use the key... To be even more explict, take everything after the `/d/` and before the `/edit`, and just use that for the key...

**Comment by kylebakerio** [comment]
Can't help you man. Not going to read and work on your code for you... Not sure why you have three init statements, but it's asking too much to expect me to decipher that. You need to provide small, tightly organized code samples if you want help, not just a wall of code.

Also, please use markdown properly to display code in a readable format.

**Comment by erikawashere** [comment]
ah, got it.  Sorry, I was in a rush and think I accidentally highlighted
everything and sent it out. But I see the issue now, so thanks!

**Comment by j2l** [comment]
@kylebakerio thanks! You saved my day.
