### ISSUE TITLE
No Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by FakeBounce** [jsoma/tabletop#160]
Code : 
`
        Tabletop.init( { key: '1VgBWvm0uKuNedA3mS98NUcZNMLucYL9I64Jinly6Pvc',
            callback: (data, tabletop) => {
                console.log('data')
                console.log(data)
                console.log(tabletop)
            },
            simpleSheet: true } )
`
Response :
Failed to load https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://spreadsheets.google.com/feeds/worksheets/1VgBWvm0uKuNedA3mS98NUcZNMLucYL9I64Jinly6Pvc/public/basic?alt%3Djson&followup=https://spreadsheets.google.com/feeds/worksheets/1VgBWvm0uKuNedA3mS98NUcZNMLucYL9I64Jinly6Pvc/public/basic?alt%3Djson&ltmpl=sheets: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Same with https://docs.google.com/spreadsheets/d/1VgBWvm0uKuNedA3mS98NUcZNMLucYL9I64Jinly6Pvc/edit?usp=sharing and https://docs.google.com/spreadsheets/d/1VgBWvm0uKuNedA3mS98NUcZNMLucYL9I64Jinly6Pvc/

**Comment by jsoma** [comment]
When putting in a new feature, I ran into this issue. I doubled-checked that I had published the spreadsheet (I hadn't!) and then it worked fine. Let me know if after publishing it still has this problem, in which case I'll explore further.
