### ISSUE TITLE
Issues Today

### ISSUE THREAD

**Issue by fredyagomez** [jsoma/tabletop#164]
It was working find yesterday.

Today I am getting this error.

![image](https://user-images.githubusercontent.com/22927931/56935422-d360df00-6aa5-11e9-9341-6b7bac9d151a.png)

**Comment by Kaktug** [comment]
I'm having the same issue, unfortunately. 
![tabletop](https://user-images.githubusercontent.com/17927046/56935679-a2da6e80-6ac0-11e9-975b-40dab1bbf7da.PNG)

Just started today with the `GET 500` errors.

**Comment by williamahartman** [comment]
Same thing here.

![image](https://user-images.githubusercontent.com/7718837/56935724-fbaa0700-6ac0-11e9-899e-cb6d973f099b.png)

The problem URL comes up fine when I open it directly in Firefox. Oddly, I only see the 500 when I open the page in Chrome or use a REST client...

**Comment by fredyagomez** [comment]
The url used to query Google sheet returns **Internal Error** both in Firefox and Chrome

https://spreadsheets.google.com/feeds/worksheets/1a_kqOPncDyMm-Lrw0FsmRNLgfk0a0j7SW7A4VgQtax0/public/basic?alt=json

Hence data is undefined and it fails.

Wonder if Google decided to change the API to make the request.

**Comment by TamaEaston** [comment]
I've run into an identical issue with Tabletop generated URLs in the https://spreadsheets.google.com/feeds/worksheets/1XKEoNootdqppngBRDnfoj0qjrdfCGcprqegMaLsZs24/public/basic?alt=json format now returning a 500 error.

It looks like Google have changed something at their end. But I don't know if this is a temporary bug or a permanent change to their services.

**Comment by keldenl** [comment]
Running into the same issues right now, didn't change anything about my code and suddenly stopped working.

**Comment by yfxie** [comment]
hey guys, I just hotfix the issue by using https://www.papaparse.com/ to read CSV files from public CSV URL.

<img width="553" alt="Screen Shot 2019-04-30 at 12 12 44 PM" src="https://user-images.githubusercontent.com/2563230/56943299-702c8680-6b51-11e9-9ab3-83ab7bb1fcfd.png">

by clicking File -> Publish then you will see the screen like above.
I believe this way should be stable than Tabletop.

**Comment by ObiJanKenobi** [comment]
Looks to me like the problem is this:
`<errors xmlns="http://schemas.google.com/g/2005">
<error>
<domain>GData</domain>
<code>BadRequestException</code>
<internalReason>
The Doclist API has been shut down. Please use the new Drive API, https://developers.google.com/drive/.
</internalReason>
</error>
</errors>`

**Comment by empirerhythmics** [comment]
I have the same issue. It looks like it is something that Google changed on their end. Does anybody have any ideas of how to get around this?

**Comment by kevincassidy313** [comment]
I'm seeing the same issue also. Would be great if someone knows the simplest fix.

**Comment by Mariorossi4316** [comment]
Same issue here.

**Comment by jeandav** [comment]
same tbh

**Comment by Kaktug** [comment]
For now I've reverted to using a JSON export of my sheet.  Here's what I'm working with:

Using the Export Sheets add-on:
https://chrome.google.com/webstore/detail/export-sheet-data/bfdcopkbamihhchdnjghdknibmcnfplk?hl=en

Dump a JSON file out to disk, then I've replaced my tabletop instantiation with:

```
function loadJSON(callback){
  var xobj = new XMLHttpRequest();
  xobj.overrideMimeType('application/json');
  xobj.open('GET', 'LICENSE_FILE_PATH_OR_URL_HERE', true);
  xobj.onreadystatechange = function() {
    if(xobj.readyState == 4 && xobj.status == '200') {
      callback(xobj.responseText);
    }
  };
  xobj.send(null);
}

function init() {
  loadJSON(function(response) {
    data = JSON.parse(response);
    console.log(data);
    [...YOUR_CODE_HERE...]
  });
}

window.onLoad=init();
```
}

It's a lot less friendly than tabletop, but if you're like me and need an immediate solution this is pretty workable without tearing apart your original source code.

**Comment by kevincassidy313** [comment]
I only had about 10 web pages using TableTop, so I've switched them all over to Airtable instead of Sheets/TableTop this morning (took about 10 minutes per page). Seems like a more reliable solution (and loads a lot quicker).

**Comment by lukegreaves5** [comment]
I passed in debug:true and there doesn't seem to be any support for this issue. This is what the console is giving me

<img width="539" alt="Screen Shot 2019-04-30 at 8 04 54 AM" src="https://user-images.githubusercontent.com/38199499/56960445-c7fdca00-6b1e-11e9-908a-75fab67fbfd4.png">

**Comment by edwardbattistini** [comment]
having the same issue. Has google killed the json parameter ?

**Comment by ErikBoesen** [comment]
Same problem.

**Comment by xeophin** [comment]
I found the issue on Google's issue tracker: https://issuetracker.google.com/issues/131613284

So far I haven't seen any answers from Google to address the issue.

Seems like the problem only occurs when using version 3 of the Spreadsheet API, with v4 (which is used by Sheetrock), everything works as before.

As v3 is marked as deprecated, it is possible that Google will decide to drop support entirely, which would require a rewrite of Tabletop.js to use v4 of the API.

**Comment by williamahartman** [comment]
Sounds like they're looking into it: https://issuetracker.google.com/issues/131613284#comment82

**Comment by Mariorossi4316** [comment]
"The engineering team believes they have located the source of the problem and are rolling back to a previous build in order to resolve issue. Please stand by."
Apr 30, 2019 05:30PM

https://issuetracker.google.com/issues/131613284#comment109

**Comment by lukegreaves5** [comment]
It is working again!

**Comment by ErikBoesen** [comment]
@fredyagomez  recommend closing.

**Comment by fredyagomez** [comment]
Closing.
