### ISSUE TITLE
Spreadsheet with 2 sheets seems to randomly display one or the other

### ISSUE THREAD

**Issue by philmetzger** [jsoma/tabletop#167]
I have a single spreadsheet with 2 sheets: classes and events.

Now on my index page I have this defined:

```
function init() {
                    Tabletop.init( { key: publicSpreadsheetUrl,
                        callback: showInfo, wanted: ['classes'] } )
                }
```

However it seems to randomly change to showing either the classes sheet or the events sheet. Any idea why?

**Comment by jsoma** [comment]
Sorry, not enough to reproduce here - I know it's a million years later, but if you can set me up with the actual spreadsheet URL you used so I'd love to reopen and take a look.
