### ISSUE TITLE
Objects are columns, not rows

### ISSUE THREAD

**Issue by Arifd** [jsoma/tabletop#170]
Hello,

I want the objects to be organised by columns, so that I can select a random object, run a loop on the object array, based on array.length, and return a random value (Each column could have a varying number of entries)

Right now, since I don't think Tabletop has a {mode: column} my workaround is to organise the data in my spreadsheet horizontally, and give them a rather arbitary numeric 'title'

i.e.

| 0 | 1 | 2 | 3 | 4 | 5 |
|---|---|---|---|---|---|
| Animals | dog | cat | mouse | elephant | lion |
| Foods | pizza | pasta | | | |
| Countries | Denmark | Swizterland | Atlantis | |

But this is clunky. It's not intuitive or effective to maintain my database this way when it grows, and when the information arrives in Tabletop Every object's array's first index needs to be discarded and I need to recalculate the array.legth since rows that contain less than others will have array values with "" in them.

Have you considered a {mode: column} could this be possible to build?

**Comment by jsoma** [comment]
Won't be integrating this into Tabletop, but I tweaked [this SO answer](https://stackoverflow.com/a/42881009) for you to show you how to transpose a list of objects:

```
const objects = [
  {'name': 'A', 'value': 1 },
  {'name': 'B' },
  {'name': 'C', 'value': 3 },
  {'name': 'D', 'value': '' },
]

// Get the keys
const keys = Object.keys(objects[0])
// Turn them into a list of objects
const mapped = keys.map( function(key) {
    // Get the key's value for each existing object, only keep non-empty ones
    return ({ [key]: objects.map( o => o[key] ).filter( value => value ) })
})
// Turn that list into an object
const results = Object.assign(...mapped)
```

**Comment by Arifd** [comment]
Thank you for your swift and helpful response!
