### ISSUE TITLE
stops at empty rows

### ISSUE THREAD

**Issue by Mik-A** [jsoma/tabletop#178]
If there is an empty row in the sheet, Tabletop ignores everything that comes after. Using simpleSheet: false and manually trying to find relevant data does not help.
if the first row is empty then it stops there and find no data at all.

if the first row has only one column populated (like a heading etc.) then it will read only that column (eg. A)

ps. support for many tables is also missing.

**Comment by jsoma** [comment]
Unfortunately, last I checked it's actually that Google stops sending data when it hits an empty row.
