### ISSUE TITLE
Trouble accessing specific sheet data

### ISSUE THREAD

**Issue by cheelay** [jsoma/tabletop#182]
When I set simpleSheet: true, I am able to append data with code like this:

`$(".dataRank").append(data[0].Rank);`

But when I set simpleSheet: false, I get an error when I try to append data with code like this:

`$(".dataRank").append(tabletop.sheets("HW")[0].Rank);`

The error I receive is: "Uncaught (in promise) TypeError: Cannot read property 'sheets' of undefined".

I am quite new to coding, so any guidance would be appreciated.

**Comment by cheelay** [comment]
I can access multiple worksheet data with code like:

`$(".dataRank").append(data.HW.elements[0].Rank);`

That's good enough for me. I just wondered why the .sheets function wasn't working.

**Comment by jsoma** [comment]
Not quite sure but it's possibly because when you created your callback, you used `function(data)` and forgot to adjust it to `function(data, tabletop)`. Glad you got it working!
