### ISSUE TITLE
Google sheets data export only for paid version?

### ISSUE THREAD

**Issue by jimver04** [jsoma/tabletop#185]
Hi, 

It seems that tabletop.js is not working for new Google sheets. The "publish to web" option in GSheets does not publish any data but only the title of the document. This is not the case for old GSheets that still provide data.

From a temporary search, the option to publish data seems to belong to the paid version of G Suite.  Can you confirm ?

Best, 
D.

**Comment by jimver04** [comment]
False alarm. It still works. I think that the "Publish to web" button has a bug in certain cases. Though I have not found the bug, the publish to web seems to work today and tabletop works fine.

**Comment by mh453Uol** [comment]
@jimver04 Can you close the issue then, thanks!
