### ISSUE TITLE
How to retrieve sheet order

### ISSUE THREAD

**Issue by rinopo** [jsoma/tabletop#32]
Scratched my head a couple of hours finding how to retrieve the sheets in the order they are ordered in the spreadsheet.

I could finally achieve it by using <code>tableTop.foundSheetNames</code>, but shouldn't it be documented since the values of <code>tableTop.model_names</code> seem to come in a random order (maybe in the order of asynchronous retrieval)?

Cheers,

**Comment by CaptainT33mo** [comment]
Can someone please post how to use the `tableTop.foundSheetNames`? I am using this:
```javascript
Tabletop.init( {
    key: 'https://docs.google.com/spreadsheets/d/0AmYzu_s7QHsmdDNZUzRlYldnWTZCLXdrMXlYQzVxSFE/pubhtml',
    simpleSheet: true }
  ).then(function(data, tabletop) { 
    console.log(data)
  })
```
and in the above code at line `then(function(data, tabletop)` the `tabletop` is coming `undefined` always so I am not sure how am I supposed to use `tableTop.foundSheetNames`.
