### ISSUE TITLE
Tabletop is undefined in Internet Explorer 9

### ISSUE THREAD

**Issue by AndrewGibson27** [jsoma/tabletop#56]
I'm getting a SCRIPT 5009: Tabletop is undefined error in IE9.

The following is contained in a script tag just before the closing body tag. Any thoughts?

start();

function start() 
{  
    var url = 'MY_URL_IS_HERE';
    Tabletop.init( 
        { 
            key: url,
            callback: fillBarker,
            simpleSheet: true 
        }
    );
}

**Comment by zero0Halo** [comment]
I'm also experiencing the same bug.

**Comment by jsoma** [comment]
Sorry to hear that! Do you get the same error when using code from the `/examples/` directory?
