### ISSUE TITLE
retry failed requests

### ISSUE THREAD

**Issue by mastef** [jsoma/tabletop#61]
Sometimes with multiple spreadsheets the request might time-out, or the proxy might fail.

Is there any way to force a retry on the failed request / handle the error?

**Comment by bhardy** [comment]
Used this for a client and I'd love this as well. He was using a wordpress plugin to do the same thing and it was failing at a very high rate. Tabletop is working much better but it still gets the odd failure. His budget is out so I can't help ( :-1: ) but if this was added I'd definitely update.

**Comment by jsoma** [comment]
There's some error handling now that can help folks DIY this.
