### ISSUE TITLE
Sorttable.js Compatibility

### ISSUE THREAD

**Issue by DaveyJake** [jsoma/tabletop#72]
I'm not sure why but it seems that Tabletop breaks Sorttable even though Sorttable is pure JS and doesn't require any external library to function.

Any ideas on why this is happening or how to fix it?

The raw text file can be found here: http://www.kryogenix.org/code/browser/sorttable/sorttable.js

**Comment by jsoma** [comment]
It looks like Sorttable overwrites the window initialization with the line `window.onload = sorttable.init` - are you using that method to initialize Tabletop? If both overwrite it then only one can survive! A better solution is along the lines of 

````
window.addEventListener("load", function(){ 
    console.log("loaded"); 
})
````
