### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by nescalante** [jsoma/tabletop#74]
Nowadays, Tabletop works with NodeJS using the **request** module. But when using browserify, **request** became a big package (and consequently Tabletop too) and the resulting bundle is a ~1MB file (which is a bit huge for a client side file).

**Comment by gamecubate** [comment]
<bump> and ditto on that.

**Comment by jsoma** [comment]
I'm open to a pull request if anyone wants to lend a hand or recommend an alternative way of doing things.

**Comment by FredKSchott** [comment]
If you want to use request on the browser /w browserify, check out https://github.com/maxogden/nets

**Comment by nescalante** [comment]
I created my own version of a Spreadsheet reader based on Tabletop while this issue is discussed:
https://github.com/nescalante/gsx
