### ISSUE TITLE
Ember.js Support

### ISSUE THREAD

**Issue by udithishara** [jsoma/tabletop#75]
Does tabletop supports ember.js with ember-data ?

i've been using tabletop for simple static stuff for while now and i'm trying to get it to work with ember. so far no luck, if it is possible could you put up a demo page for that like the backbone one please ?

**Comment by nruth** [comment]
You can do this with Routes and Promises by passing an Ember promise's resolve callback into Tabletop init. Here's how I got it to work with a hard-coded key. I've not done dynamic key lookup yet, but it'll probably be using needs and a parent controller w/ nested routes:

```coffee
Route = Ember.Route.extend
  model: ->
    new Ember.RSVP.Promise( (resolve, reject)->
      resolveSheet = ((sheets, tabletop)->
        Ember.run ->
          Ember.run.schedule 'actions', this, ->
            console.log 'received data', sheets
            resolve(sheets)
      )

      Tabletop.init(
        key: 'document-key-or-url'
        simpleSheet: false
        callback: resolveSheet
        debug: true
      )
    )
```

I don't know if the run loops usage is correct but it seems to work.
