### ISSUE TITLE
Not really an issue but a comment

### ISSUE THREAD

**Issue by DaveyJake** [jsoma/tabletop#77]
Just wanted to say Tabletop.js works great with [jQuery Brackets](http://www.aropupu.fi/bracket/)!  The area I'm struggling with is figuring out how to send edited data, made using [jQuery Brackets](http://www.aropupu.fi/bracket/) on a website, to the original Google Spreadsheet.

The API to edit jQuery Bracket data can be viewed [here](http://www.aropupu.fi/bracket/#save). Any ideas on how to achieve this would be greatly appreciated.

Thank you for your time and keep up the great work!

**Comment by jsoma** [comment]
Also, thank YOU!
