### ISSUE TITLE
Unclear instructions?

### ISSUE THREAD

**Issue by TheChymera** [jsoma/tabletop#78]
The README seems rather content in stating that this "just works like so:". I cloned the repo, rsynced it to my server, and added an `index.html` file to the tabletop root directory, which contains:

```
<!DOCTYPE html>
<html>
<body>
<script type="text/javascript">
  window.onload = function() { init() };

  var public_spreadsheet_url = 'https://docs.google.com/spreadsheet/pub?hl=en_US&hl=en_US&key=0AmYzu_s7QHsmdDNZUzRlYldnWTZCLXdrMXlYQzVxSFE&output=html';

  function init() {
    Tabletop.init( { key: public_spreadsheet_url,
                     callback: showInfo,
                     simpleSheet: true } )
  }

  function showInfo(data, tabletop) {
    alert("Successfully processed!")
    console.log(data);
  }
</script>
</body>
</html>
```

This shows me a blank page. 
What am I missing?

**Comment by jsoma** [comment]
In that particular case you'll want to include the tabletop.src file, but
give a shot at checking out the examples hanging out in /examples/ -
they'll hopefully do a halfway-decent job working you through some
possibilities. Let me know if that still doesn't clear things up, though!
