### ISSUE TITLE
apps broke; npm version different

### ISSUE THREAD

**Issue by mroswell** [jsoma/tabletop#85]
My existing tabletop apps broke with a 500 error when accessing the sheet json. 
My best guess is that Google automatically updated to "new" sheets.

- when I installed the latest tabletop.js from here it didn't fix the issue 
- when I installed the latest tabletop.js from npm install, it did fix the issue.

Some questions:
- How can we detect which version of Google Sheets a given spreadsheet uses?
- What accounts for the npm install version being different than the repo version? Are there guidelines for which to use when?
- Is anyone else experiencing broken apps (without having touched the code for a long time)
- Is Google sheets automatically updating sheets? Might it happen upon loading the sheet?
(Google documentation says "*Spreadsheets created in the old version of Sheets will eventually be converted to the new Sheets, which won’t require any action on your part. More details coming soon."
https://support.google.com/docs/answer/3544847?hl=en

**Comment by jengalas** [comment]
My app broke last week too and I also connected it to Google automatically updating the spreadsheet to the new version. I was able to fix it with two simple changes. Check these items and see if they get you going in the right direction:
* Previously we had to account for the change in spreadsheet column headers that used capital letters or symbols (for example, "Building Name" became "buildingname). In a recent version of Tabletop, an option was added to the init to allow for "pretty column names" and it defaults to true. So if this is your issue, you'll want to either set ```prettyColumnNames``` to ```false``` when you initialize Tabletop, or modify your template to use the "pretty" names.
* If you're using Flatware as a proxy you'll need to update that too, to work with the new Sheets.

Also, check your spreadsheet key, just in case. Mine changed, but I think the old one also continues to work. 

I haven't compared the code between the npm and GitHub versions, but the npm version appears to be older and may not contain ```prettyColumnNames```.

**Comment by aendrew** [comment]
@jengalas PrettyColumns are only in 1.4.0 (AFAIK). Most of the issues I've had with TT recently have been due to that, particularly in relation to Flatware.

**Comment by jsoma** [comment]
Just pushed a new version to npm, let me know if you're still experiencing issues (along with the above suggestions).

**Comment by mroswell** [comment]
- How can we detect which version of Google Sheets a given spreadsheet uses?
- How do we upgrade an old version of Google Sheets?
- If we have an old sheet, how do we access the correct version of NPM install? Are there guidelines for which version to use when?

**Comment by jsoma** [comment]
Tabletop should work automatically for both old and new versions of Sheets. I*think* all old spreadsheets have been automatically upgraded, though (a notice will be in the bottom right when you open it up).

Have you checked your publish keys? Do you use Flatware?
