### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by aendrew** [jsoma/tabletop#87]
It amazes me that something I've used in production like a bajillion times in production doesn't have a single unit test. Issues like #80 could be prevented entirely if a decent test suite was added. 

@jsoma If this interests you, please let me know — I like writing tests and would love to add some to Tabletop.

**Comment by jsoma** [comment]
I'd love some tests! Tabletop has grown really organically and I might have a tendency to play a *little* too fast-and-loose with it.

**Comment by aendrew** [comment]
Cool, thanks! I have a bunch of time at the moment, will setup the testing through grunt next chance I get!
