### ISSUE TITLE
Column Header Naming in Google Spreadsheets

### ISSUE THREAD

**Issue by grayghostvisuals** [jsoma/tabletop#91]
How does this work currently? It seems column headers are not able to be named in Google Spreadsheets. What am I missing?

**Comment by jsoma** [comment]
Could you give an example of your problem? The column headers should come through as the object keys (e.g. `.title` and `.cost` from [this example](https://github.com/jsoma/tabletop/blob/master/examples/simple/standard.html)).

**Comment by grayghostvisuals** [comment]
The column headers for Google spreadsheets cannot have the headers renamed from what I'm seeing so far. When I fill in the cells with data (2 cells to be exact) I still get no data returned. This doc [here](https://docs.google.com/spreadsheets/d/1cdA0o91aibcohbieeFoVauytkW4ZvDh_f5kwGPzZLxU/pubhtml) returns no data for me on the model.

```javascript
window.onload = function() { init() };
  var public_spreadsheet_url = 'https://docs.google.com/spreadsheets/pub?hl=en_US&hl=en_US&key=1cdA0o91aibcohbieeFoVauytkW4ZvDh_f5kwGPzZLxU&output=html';

  function init() {
    Tabletop.init( { key: public_spreadsheet_url,
                     callback: showInfo,
                     simpleSheet: true } ) // tried false as well with no luck.
  }

  function showInfo(data, tabletop) {
    console.log(data);
  }
```
