### ISSUE TITLE
invalid public spreadsheet key results in crash

### ISSUE THREAD

**Issue by sleepyspider1** [jsoma/tabletop#96]
GET https://spreadsheets.google.com/feeds/worksheets/1lIo2calXb_GtaQ/public/basic?alt=json 400 (OK)Tabletop.xhrFetch @ tabletop.js:185Tabletop.requestData @ tabletop.js:162Tabletop.fetch @ tabletop.js:146Tabletop @ tabletop.js:124Tabletop.init @ tabletop.js:133on_click_import_button @ options.js:215v.event.dispatch @ jquery.js:2v.event.add.o.handle.u @ jquery.js:2
tabletop.js:181 SyntaxError: Unexpected token T
    at Object.parse (native)
    at XMLHttpRequest.Tabletop.xhrFetch.xhr.onload (chrome-extension://ggkonjneghcddicojapdfelfhilompae/js/tabletop.js:179:27)

```
loadSheets: function(data) {
  var i, ilen;
  var toLoad = [];
  this.foundSheetNames = [];

  for(i = 0, ilen = data.feed.entry.length; i < ilen ; i++) {
```

data is undefined if the spreadsheet key is invalid. I would rather it return an error or some indication that it failed rather than just crashing if the key is invalid.

**Comment by jsoma** [comment]
It's sixty or seventy years later, but we have error handling now!
